# Kalman

In [1]:
import numpy as np
from numpy.linalg import inv

def kalman(h,f,p,x,z,r,b,u):
    Q_matrix = 0
    # Calc X
    x = f*x+b*u
    # Calc P
    p = f*p*f.T + Q_matrix
    # Update
    S = h*p*h.T + r
    S = inv(S)
    K = p*h.T*S
    x = x + K*(z-h*x)
    p = p-K*h*p
    return x,p
    
if __name__ == "__main__":
    # H matrix
    factor = 1.0
    hM = np.matrix([[factor,0,0,0],[0,factor,0,0]])
    # P matrix
    stdPos = 7
    velocityPos = 100
    pM = np.matrix([[stdPos**2,0,0,0],[0,stdPos**2,0,0],[0,0,velocityPos**2,0],[0,0,0,velocityPos**2]])
    # X matrix
    initialXPos_guess = 200
    initialYPos_guess = 150
    initialVelocity_guess = 0
    xM = np.matrix([[initialXPos_guess],[initialYPos_guess],[initialVelocity_guess],[initialVelocity_guess]])
    # R matrix
    std_sensor = 6
    rM = np.matrix([[std_sensor**2,0],[0,std_sensor**2]])
    # U matrix
    uM = np.matrix([[5],
                    [15]])
    # F matrix
    deltaT = 1
    fM = np.matrix([[1,0,deltaT,0],[0,1,0,deltaT],[0,0,1,0],[0,0,0,1]])
    # B
    bM = np.matrix([[1/2*deltaT**2, 0], # after multiply with U matrix: ax*(1/2)t^2
                         [0,1/2*deltaT**2], # after multiply with U matrix: ay*(1/2)t^2
                         [deltaT,0],        # after multiply with U matrix: ax*t
                         [0,deltaT]])       # after multiply with U matrix: ay*t
    
    # set the measurements from the sensor for iteration
    measurements = [[240,204],[284,267],[334,344],[390,437],[450,544],[516,667]]
    for i in range(0,6):
        # Update Z matrix
        zM = np.matrix([[measurements[i][0]],[measurements[i][1]]])
        # Call kalman method
        xM,pM = kalman(hM,fM,pM,xM,zM,rM,bM,uM)
        print("----------------------------------")
        print("Iteration number", i+1)
        print("----------------------------------")
        print("State Vector is:\n", xM)
        print("\nP matrix is:\n", pM)
    

----------------------------------
Iteration number 1
----------------------------------
State Vector is:
 [[239.86613783]
 [203.83401091]
 [ 42.18393654]
 [ 61.10808131]]

P matrix is:
 [[35.87149232  0.         35.69657908  0.        ]
 [ 0.         35.87149232  0.         35.69657908]
 [35.69657908  0.         84.28358949  0.        ]
 [ 0.         35.69657908  0.         84.28358949]]
----------------------------------
Iteration number 2
----------------------------------
State Vector is:
 [[284.08702628]
 [267.86098367]
 [ 46.89389687]
 [ 73.23861002]]

P matrix is:
 [[30.3045044   0.         18.98184785  0.        ]
 [ 0.         30.3045044   0.         18.98184785]
 [18.98184785  0.         21.02121993  0.        ]
 [ 0.         18.98184785  0.         21.02121993]]
----------------------------------
Iteration number 3
----------------------------------
State Vector is:
 [[333.8508512 ]
 [345.32162295]
 [ 52.05963047]
 [ 86.77002745]]

P matrix is:
 [[25.6559502   0.         11.