# Kalman

In [1]:
import numpy as np
from numpy.linalg import inv

In [2]:
a = np.matrix([[1,0],[0,1]])
a.T

matrix([[1, 0],
        [0, 1]])

# Initial F-Matrix, P-Matrix, State-Vector

In [3]:
stdPos = 2
stdVel = 1.2
pMatrix = np.matrix([[stdPos**2,0],[0,stdVel**2]])

deltaT = 1.0
fMatrix = np.matrix([[1,deltaT],[0,1]])

initialPos_guess = 8
initialVelocity_guess = 5
x = np.matrix([[initialPos_guess],[initialVelocity_guess]])

print("F matrix is:\n", fMatrix)
print("\nP matrix is:\n", pMatrix)
print("\nState Vector is:\n", x)

F matrix is:
 [[1. 1.]
 [0. 1.]]

P matrix is:
 [[4.   0.  ]
 [0.   1.44]]

State Vector is:
 [[8]
 [5]]


# After Prediction

In [4]:
Q_matrix = 0
I = np.matrix([[1,0],[0,1]])
x = fMatrix*x
pMatrix = fMatrix*pMatrix*fMatrix.T + Q_matrix

print("After Prediction:\n")

print("\nP matrix is:\n", pMatrix)
print("\nState Vector is:\n", x)

After Prediction:


P matrix is:
 [[5.44 1.44]
 [1.44 1.44]]

State Vector is:
 [[13.]
 [ 5.]]


#  Print R-Matrix, H-Matrix, meassurment(z)

In [5]:
factor = 1./0.3048
std_sensor = 0.5
velocity_sensor = 4
# R_matrix = np.matrix([std_sensor**2])
R_matrix = np.matrix([[std_sensor**2,0],[0,velocity_sensor**2]])
H_matrix = np.matrix([[factor,0],[0,1.0]])
z = np.matrix([[43],[4]])

print("R matrix is:\n", R_matrix)
print("\nH matrix is:\n", H_matrix)
print("\nmeassurment (z) is:\n", z)

R matrix is:
 [[ 0.25  0.  ]
 [ 0.   16.  ]]

H matrix is:
 [[3.2808399 0.       ]
 [0.        1.       ]]

meassurment (z) is:
 [[43]
 [ 4]]


# After Update

In [6]:
S = H_matrix*pMatrix*H_matrix.T + R_matrix
# print("S matrix:\n", S)
S = inv(S)
# print("S matrix Reverse:\n", S)

# print("\nP matrix is:\n", pMatrix)
# print("H matrix.T is:\n", H_matrix.T)
# print("S matrix is:\n", S)

K = pMatrix*H_matrix.T*S

x = x + K*(z-H_matrix*x)

# print("P matrix:\n", pMatrix)
# print("K*H_matrix matrix*pMatrix:\n", K*H_matrix*pMatrix)

pMatrix = (I - K*H_matrix)*pMatrix

print("After Update:")

print("\nP matrix is:\n", pMatrix)
print("\nState Vector is:\n", x)
print("\nNew Kalman Gain (K) is:\n", K)

After Update:

P matrix is:
 [[0.02312482 0.00574134]
 [0.00574134 0.99452888]]

State Vector is:
 [[13.10557877]
 [ 4.96414369]]

New Kalman Gain (K) is:
 [[0.30347538 0.00035883]
 [0.07534561 0.06215806]]
